### ISSUE TITLE
Build issues with more modern clang

### ISSUE THREAD

**Issue by magnesj** [CeetronSolutions/openzgy#5]
Building using clang-16 and clang-17 causes issues.

Seen here using clang-17
https://github.com/magnesj/ResInsight/actions/runs/7337493679/job/19978457025

**Comment by magnesj** [comment]
Fix in private repo here
https://github.com/magnesj/openzgy

**Comment by jonjenssen** [comment]
Awaiting upstream patch to be accepted, will be closed by #6
